<!DOCTYPE raiz1
[
<!ELEMENT raiz1 (ALUMNO)>
<!ELEMENT ALUMNO (NOMBRE,GANASDETRABAJAR)>
<!ELEMENT NOMBRE (#PCDATA)>
<!ELEMENT GANASDETRABAJAR EMPTY>
]>


<raiz1>
    <ALUMNO>
        <NOMBRE>JORGE</NOMBRE>
        </GANASDETRABAJAR></GANASDETRABAJAR>
    </ALUMNO>
</raiz1>
