=== AlejandroZF10/Web-Application/Practice37/build/web/usersDTD.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT root (user)*>
<!ELEMENT user (name|password)*>
<!ATTLIST user
    id CDATA #IMPLIED
    type CDATA #IMPLIED
  >
<!ELEMENT name (#PCDATA)>
<!ELEMENT password (#PCDATA)>

=== AlejandroZF10/Web-Application/Practice37/build/web/users.xml
<?xml version="1.0"?>
<!DOCTYPE root SYSTEM "usersDTD.dtd">
<root>
    <user id="0" type="1">
        <name>ajitzi</name>
        <password>ricardo</password>
    </user>
    <user id="1" type="2">
        <name>jony</name>
        <password>elmejor</password>
    </user>
    <user id="2" type="3">
        <name>lastiri</name>
        <password>ni√±ita</password>
    </user>
    <user id="4" type="2">
        <name>arvid</name>
        <password>12345</password>
    </user>
    
</root>
